# Generated by Django 5.1.7 on 2025-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '발행')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
