# Generated by Django 5.1.7 on 2025-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '발행')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
